//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaticIndustries.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsiaticIndustries.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer Failed.
        /// </summary>
        public static string AddCustomerFailed {
            get {
                return ResourceManager.GetString("AddCustomerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer Succeeded.
        /// </summary>
        public static string AddCustomerSucceeded {
            get {
                return ResourceManager.GetString("AddCustomerSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is added successfully..
        /// </summary>
        public static string AddCustomerSuccessMessage {
            get {
                return ResourceManager.GetString("AddCustomerSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Failed.
        /// </summary>
        public static string AddProductFailed {
            get {
                return ResourceManager.GetString("AddProductFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product Sample Failed.
        /// </summary>
        public static string AddProductSampleFailed {
            get {
                return ResourceManager.GetString("AddProductSampleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Raw Material Failed.
        /// </summary>
        public static string AddRawMaterialFailed {
            get {
                return ResourceManager.GetString("AddRawMaterialFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address can not exceed 200 characters..
        /// </summary>
        public static string AddressMaxLength {
            get {
                return ResourceManager.GetString("AddressMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Failed.
        /// </summary>
        public static string AddUserFailed {
            get {
                return ResourceManager.GetString("AddUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User Succeeded.
        /// </summary>
        public static string AddUserSucceeded {
            get {
                return ResourceManager.GetString("AddUserSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is added successfully..
        /// </summary>
        public static string AddUserSuccessMessage {
            get {
                return ResourceManager.GetString("AddUserSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Admin over head price (100%). Price should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string AdminOverHeadPriceInvalid {
            get {
                return ResourceManager.GetString("AdminOverHeadPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin over head price (100%)  can not exceed 13 characters. Price should contain max 10 digit left and 2 digit rigth to decimal point..
        /// </summary>
        public static string AdminOverHeadPriceMaxLength {
            get {
                return ResourceManager.GetString("AdminOverHeadPriceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin over head price (100%) is required..
        /// </summary>
        public static string AdminOverHeadPriceRequired {
            get {
                return ResourceManager.GetString("AdminOverHeadPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RK number can not exceed 100 characters..
        /// </summary>
        public static string AINumberMaxLength {
            get {
                return ResourceManager.GetString("AINumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RK number is required..
        /// </summary>
        public static string AINumberRequired {
            get {
                return ResourceManager.GetString("AINumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asiatic Industries | .
        /// </summary>
        public static string AsiaticIndustries {
            get {
                return ResourceManager.GetString("AsiaticIndustries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid commision. It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string CommissionInvalid {
            get {
                return ResourceManager.GetString("CommissionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission  can not exceed 6 characters. It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string CommissionMaxLength {
            get {
                return ResourceManager.GetString("CommissionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have 8-20 characters..
        /// </summary>
        public static string ConfirmPasswordMaxLength {
            get {
                return ResourceManager.GetString("ConfirmPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is required..
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard quantity.Quantity should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string CrudePriceInvalid {
            get {
                return ResourceManager.GetString("CrudePriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard quantity can not exceed 13 characters.Quantity should contain max 10 digit left and 2 digit right to decimal point. .
        /// </summary>
        public static string CrudePriceMaxLength {
            get {
                return ResourceManager.GetString("CrudePriceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid crude price. Price should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string CrudePricePerKgInvalid {
            get {
                return ResourceManager.GetString("CrudePricePerKgInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crude price  can not exceed 13 characters. Price should contain max 10 digit left and 2 digit rigth to decimal point. .
        /// </summary>
        public static string CrudePricePerKgMaxLength {
            get {
                return ResourceManager.GetString("CrudePricePerKgMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crude price is required..
        /// </summary>
        public static string CrudePricePerKgRequired {
            get {
                return ResourceManager.GetString("CrudePricePerKgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard  quantity is required..
        /// </summary>
        public static string CrudePriceRequired {
            get {
                return ResourceManager.GetString("CrudePriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current USD rate. current USD rate should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string CurrentUSDRateInvalid {
            get {
                return ResourceManager.GetString("CurrentUSDRateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current USD rate  can not exceed 13 characters. USD rate should contain max 10 digit left and 2 digit right to decimal point. .
        /// </summary>
        public static string CurrentUSDRateMaxLength {
            get {
                return ResourceManager.GetString("CurrentUSDRateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current USD rate is required..
        /// </summary>
        public static string CurrentUSDRateRequired {
            get {
                return ResourceManager.GetString("CurrentUSDRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is disabled successfully,.
        /// </summary>
        public static string CustomerDisabledSuccessfully {
            get {
                return ResourceManager.GetString("CustomerDisabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Disable Succeeded.
        /// </summary>
        public static string CustomerDisableSucceeded {
            get {
                return ResourceManager.GetString("CustomerDisableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is enabled successfully,.
        /// </summary>
        public static string CustomerEnabledSuccessfully {
            get {
                return ResourceManager.GetString("CustomerEnabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Enable Succeeded.
        /// </summary>
        public static string CustomerEnableSucceeded {
            get {
                return ResourceManager.GetString("CustomerEnableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is required..
        /// </summary>
        public static string CustomerRequired {
            get {
                return ResourceManager.GetString("CustomerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is saved successfully..
        /// </summary>
        public static string CustomerSavedSuccefully {
            get {
                return ResourceManager.GetString("CustomerSavedSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Saved Succeeded.
        /// </summary>
        public static string CustomerSaveSucceeded {
            get {
                return ResourceManager.GetString("CustomerSaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Customer.
        /// </summary>
        public static string DisableCustomer {
            get {
                return ResourceManager.GetString("DisableCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Product.
        /// </summary>
        public static string DisableProduct {
            get {
                return ResourceManager.GetString("DisableProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Product Sample.
        /// </summary>
        public static string DisableProductSample {
            get {
                return ResourceManager.GetString("DisableProductSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Quote.
        /// </summary>
        public static string DisableQuote {
            get {
                return ResourceManager.GetString("DisableQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Raw Material.
        /// </summary>
        public static string DisableRawMaterial {
            get {
                return ResourceManager.GetString("DisableRawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable User.
        /// </summary>
        public static string DisableUser {
            get {
                return ResourceManager.GetString("DisableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid discount percent.It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string DiscountPercentInvalid {
            get {
                return ResourceManager.GetString("DiscountPercentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount percent can not exceed 6 characters. It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string DiscountPercentMaxLength {
            get {
                return ResourceManager.GetString("DiscountPercentMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid discount reason.It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string DiscountReasonInvalid {
            get {
                return ResourceManager.GetString("DiscountReasonInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount reason can not exceed 6 characters. It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string DiscountReasonMaxLength {
            get {
                return ResourceManager.GetString("DiscountReasonMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can not exceed 50 characters..
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Customer.
        /// </summary>
        public static string EnableCustomer {
            get {
                return ResourceManager.GetString("EnableCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Product.
        /// </summary>
        public static string EnableProduct {
            get {
                return ResourceManager.GetString("EnableProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Product Sample.
        /// </summary>
        public static string EnableProductSample {
            get {
                return ResourceManager.GetString("EnableProductSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Quote.
        /// </summary>
        public static string EnableQuote {
            get {
                return ResourceManager.GetString("EnableQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Raw Material.
        /// </summary>
        public static string EnableRawMaterial {
            get {
                return ResourceManager.GetString("EnableRawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable User.
        /// </summary>
        public static string EnableUser {
            get {
                return ResourceManager.GetString("EnableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter different usd rate..
        /// </summary>
        public static string EnterDifferentUSDRate {
            get {
                return ResourceManager.GetString("EnterDifferentUSDRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops something went wrong. We&apos;re working on getting this fixed as soon as we can. You may be able to try again..
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name can not exceed 50 characters..
        /// </summary>
        public static string FirstNameMaxLength {
            get {
                return ResourceManager.GetString("FirstNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name can not exceed 100 characters..
        /// </summary>
        public static string HostNameMaxLength {
            get {
                return ResourceManager.GetString("HostNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name is required..
        /// </summary>
        public static string HostNameRequired {
            get {
                return ResourceManager.GetString("HostNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not active.For any help please contact an administrator..
        /// </summary>
        public static string InactiveAccount {
            get {
                return ResourceManager.GetString("InactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid interest rate.It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string InterestRateInvalid {
            get {
                return ResourceManager.GetString("InterestRateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest rate  can not exceed 6 characters. It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string InterestRateMaxLength {
            get {
                return ResourceManager.GetString("InterestRateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest rate is required..
        /// </summary>
        public static string InterestRateRequired {
            get {
                return ResourceManager.GetString("InterestRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name can not exceed 50 characters..
        /// </summary>
        public static string LastNameMaxLength {
            get {
                return ResourceManager.GetString("LastNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license has expired. To keep your account up to date please renew your license..
        /// </summary>
        public static string LicenceExpiredMessage {
            get {
                return ResourceManager.GetString("LicenceExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Error.
        /// </summary>
        public static string LicenceExpiredTitle {
            get {
                return ResourceManager.GetString("LicenceExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Succeeded.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have logged in successfully..
        /// </summary>
        public static string LoginSuccessMessage {
            get {
                return ResourceManager.GetString("LoginSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MFG over head price (100%). Price should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string MfgOverHeadPriceInvalid {
            get {
                return ResourceManager.GetString("MfgOverHeadPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFG over head price (100%)  can not exceed 13 characters. Price should contain max 10 digit left and 2 digit rigth to decimal point..
        /// </summary>
        public static string MfgOverHeadPriceMaxLength {
            get {
                return ResourceManager.GetString("MfgOverHeadPriceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFG over head price (100%) is required..
        /// </summary>
        public static string MfgOverHeadPriceRequired {
            get {
                return ResourceManager.GetString("MfgOverHeadPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Kgs. It should contain max 5 digit left and 2 digit rigth to decimal point..
        /// </summary>
        public static string NumberOfKgsInvalid {
            get {
                return ResourceManager.GetString("NumberOfKgsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not exceed 8 characters.  It should contain max 5 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string NumberOfKgsMaxLength {
            get {
                return ResourceManager.GetString("NumberOfKgsMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw material quantity(in Kg) is required..
        /// </summary>
        public static string NumberOfKgsRequired {
            get {
                return ResourceManager.GetString("NumberOfKgsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid packing cost. It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string PackingCostInvalid {
            get {
                return ResourceManager.GetString("PackingCostInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing cost  can not exceed 13 characters. It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string PackingCostMaxLength {
            get {
                return ResourceManager.GetString("PackingCostMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing cost is required..
        /// </summary>
        public static string PackingCostRequired {
            get {
                return ResourceManager.GetString("PackingCostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password do not match..
        /// </summary>
        public static string PasswordAndConfirmPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password are either not valid or not same..
        /// </summary>
        public static string PasswordConfirmPasswordProblem {
            get {
                return ResourceManager.GetString("PasswordConfirmPasswordProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Password must have 8-20 characters and include: &lt;p&gt;&lt;ul &gt;&lt;li&gt;One uppercase charachter&lt;/li&gt;&lt;li&gt;One number&lt;/li&gt;&lt;li&gt;One special character&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have 8-20 characters..
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone can not exceed 200 characters..
        /// </summary>
        public static string PhoneMaxLength {
            get {
                return ResourceManager.GetString("PhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product concentration. It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string ProductConstraintsInvalid {
            get {
                return ResourceManager.GetString("ProductConstraintsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product concentration  can not exceed 6 characters. It should contain max 3 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string ProductConstraintsMaxLength {
            get {
                return ResourceManager.GetString("ProductConstraintsMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product concentration is required..
        /// </summary>
        public static string ProductConstraintsRequired {
            get {
                return ResourceManager.GetString("ProductConstraintsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is disabled successfully..
        /// </summary>
        public static string ProductDisabledSuccessfully {
            get {
                return ResourceManager.GetString("ProductDisabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Disable Succeeded.
        /// </summary>
        public static string ProductDisableSucceeded {
            get {
                return ResourceManager.GetString("ProductDisableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is enabled successfully..
        /// </summary>
        public static string ProductEnabledSuccessfully {
            get {
                return ResourceManager.GetString("ProductEnabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Enable Succeeded.
        /// </summary>
        public static string ProductEnableSucceeded {
            get {
                return ResourceManager.GetString("ProductEnableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product name is already in use. Please try with any other product name..
        /// </summary>
        public static string ProductExistWithThisProductName {
            get {
                return ResourceManager.GetString("ProductExistWithThisProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name can not exceed 100 charachters..
        /// </summary>
        public static string ProductNameMaxLength {
            get {
                return ResourceManager.GetString("ProductNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is required..
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is required..
        /// </summary>
        public static string ProductRequired {
            get {
                return ResourceManager.GetString("ProductRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample is disabled successfully..
        /// </summary>
        public static string ProductSampleDisabledSuccessfully {
            get {
                return ResourceManager.GetString("ProductSampleDisabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Disable Succeeded.
        /// </summary>
        public static string ProductSampleDisableSucceeded {
            get {
                return ResourceManager.GetString("ProductSampleDisableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample is enabled successfully..
        /// </summary>
        public static string ProductSampleEnabledSuccessfully {
            get {
                return ResourceManager.GetString("ProductSampleEnabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Enable Succeeded.
        /// </summary>
        public static string ProductSampleEnableSucceeded {
            get {
                return ResourceManager.GetString("ProductSampleEnableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This refernce number is already in use. Please try with any other reference number..
        /// </summary>
        public static string ProductSampleExistWithThisReferenceNumber {
            get {
                return ResourceManager.GetString("ProductSampleExistWithThisReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample is required..
        /// </summary>
        public static string ProductSampleRequired {
            get {
                return ResourceManager.GetString("ProductSampleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample saved successfully..
        /// </summary>
        public static string ProductSampleSavedSuccefully {
            get {
                return ResourceManager.GetString("ProductSampleSavedSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Save Succeeded.
        /// </summary>
        public static string ProductSampleSaveSucceeded {
            get {
                return ResourceManager.GetString("ProductSampleSaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product saved successfully..
        /// </summary>
        public static string ProductSavedSuccefully {
            get {
                return ResourceManager.GetString("ProductSavedSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Save Succeeded.
        /// </summary>
        public static string ProductSaveSucceeded {
            get {
                return ResourceManager.GetString("ProductSaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile is updated successfully..
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Updated.
        /// </summary>
        public static string ProfileUpdatedTitle {
            get {
                return ResourceManager.GetString("ProfileUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid profit per kg. Price should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string ProfitPerKgInvalid {
            get {
                return ResourceManager.GetString("ProfitPerKgInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit per kg  can not exceed 13 characters. Price should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string ProfitPerKgMaxLength {
            get {
                return ResourceManager.GetString("ProfitPerKgMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit per kg is required..
        /// </summary>
        public static string ProfitPerKgRequired {
            get {
                return ResourceManager.GetString("ProfitPerKgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote is disabled successfully..
        /// </summary>
        public static string QuoteDisabledSuccessfully {
            get {
                return ResourceManager.GetString("QuoteDisabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Disable Succeeded.
        /// </summary>
        public static string QuoteDisableSucceeded {
            get {
                return ResourceManager.GetString("QuoteDisableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote is enabled successfully..
        /// </summary>
        public static string QuoteEnabledSuccessfully {
            get {
                return ResourceManager.GetString("QuoteEnabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Enable Succeeded.
        /// </summary>
        public static string QuoteEnableSucceeded {
            get {
                return ResourceManager.GetString("QuoteEnableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote is saved succefully..
        /// </summary>
        public static string QuoteSavedSuccefully {
            get {
                return ResourceManager.GetString("QuoteSavedSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Save Succeeded.
        /// </summary>
        public static string QuoteSaveSucceeded {
            get {
                return ResourceManager.GetString("QuoteSaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw material is disabled successfully..
        /// </summary>
        public static string RawMaterialDisabledSuccessfully {
            get {
                return ResourceManager.GetString("RawMaterialDisabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Disable Succeeded.
        /// </summary>
        public static string RawMaterialDisableSucceeded {
            get {
                return ResourceManager.GetString("RawMaterialDisableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw material is enabled successfully..
        /// </summary>
        public static string RawMaterialEnabledSuccessfully {
            get {
                return ResourceManager.GetString("RawMaterialEnabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Enable Succeeded.
        /// </summary>
        public static string RawMaterialEnableSucceeded {
            get {
                return ResourceManager.GetString("RawMaterialEnableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This raw material name is already in use. Please try with any other raw material name..
        /// </summary>
        public static string RawMaterialExistWithThisName {
            get {
                return ResourceManager.GetString("RawMaterialExistWithThisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw material name can not exceed 100 characters..
        /// </summary>
        public static string RawMaterialNameMaxLength {
            get {
                return ResourceManager.GetString("RawMaterialNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw material name is required..
        /// </summary>
        public static string RawMaterialNameRequired {
            get {
                return ResourceManager.GetString("RawMaterialNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid raw material price. raw material price should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string RawMaterialPriceInvalid {
            get {
                return ResourceManager.GetString("RawMaterialPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw material price can not exceed 13 characters. raw material price should contain max 10 digit left and 2 digit right to decimal point. .
        /// </summary>
        public static string RawMaterialPriceMaxLength {
            get {
                return ResourceManager.GetString("RawMaterialPriceMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw material price is required..
        /// </summary>
        public static string RawMaterialPriceRequired {
            get {
                return ResourceManager.GetString("RawMaterialPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw material is required..
        /// </summary>
        public static string RawMaterialRequired {
            get {
                return ResourceManager.GetString("RawMaterialRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw material is saved successfully..
        /// </summary>
        public static string RawMaterialSavedSuccefully {
            get {
                return ResourceManager.GetString("RawMaterialSavedSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Saved Succeeded.
        /// </summary>
        public static string RawMaterialSaveSucceeded {
            get {
                return ResourceManager.GetString("RawMaterialSaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI  number can not exceed 100 characters..
        /// </summary>
        public static string ReferenceNumberMaxLength {
            get {
                return ResourceManager.GetString("ReferenceNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI number is required..
        /// </summary>
        public static string ReferenceNumberRequired {
            get {
                return ResourceManager.GetString("ReferenceNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is required..
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid forwarding quantity. It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string StandardForwardingCostInvalid {
            get {
                return ResourceManager.GetString("StandardForwardingCostInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding quantity can not exceed 13 characters. It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string StandardForwardingCostMaxLength {
            get {
                return ResourceManager.GetString("StandardForwardingCostMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding quantity is required..
        /// </summary>
        public static string StandardForwardingCostRequired {
            get {
                return ResourceManager.GetString("StandardForwardingCostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid freight quantity. It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string StandardFreightCostInvalid {
            get {
                return ResourceManager.GetString("StandardFreightCostInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight quantity can not exceed 13 characters. It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string StandardFreightCostMaxLength {
            get {
                return ResourceManager.GetString("StandardFreightCostMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight quantity is required..
        /// </summary>
        public static string StandardFreightCostRequired {
            get {
                return ResourceManager.GetString("StandardFreightCostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard number can not exceed 100 characters..
        /// </summary>
        public static string StandardNumberMaxLength {
            get {
                return ResourceManager.GetString("StandardNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to disable this customer?.
        /// </summary>
        public static string SureToDisableCustomerMessage {
            get {
                return ResourceManager.GetString("SureToDisableCustomerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to disable this product?.
        /// </summary>
        public static string SureToDisableProductMessage {
            get {
                return ResourceManager.GetString("SureToDisableProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to disable this sample?.
        /// </summary>
        public static string SureToDisableProductSampleMessage {
            get {
                return ResourceManager.GetString("SureToDisableProductSampleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to disable this quote?.
        /// </summary>
        public static string SureToDisableQuoteMessage {
            get {
                return ResourceManager.GetString("SureToDisableQuoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to disable this raw material?.
        /// </summary>
        public static string SureToDisableRawMaterialMessage {
            get {
                return ResourceManager.GetString("SureToDisableRawMaterialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to disable this user?.
        /// </summary>
        public static string SureToDisableUserMessage {
            get {
                return ResourceManager.GetString("SureToDisableUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to enable this customer?.
        /// </summary>
        public static string SureToEnableCustomerMessage {
            get {
                return ResourceManager.GetString("SureToEnableCustomerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to enable this product?.
        /// </summary>
        public static string SureToEnableProductMessage {
            get {
                return ResourceManager.GetString("SureToEnableProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to enable this sample?.
        /// </summary>
        public static string SureToEnableProductSampleMessage {
            get {
                return ResourceManager.GetString("SureToEnableProductSampleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to enable this quote?.
        /// </summary>
        public static string SureToEnableQuoteMessage {
            get {
                return ResourceManager.GetString("SureToEnableQuoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to enable this raw material?.
        /// </summary>
        public static string SureToEnableRawMaterialMessage {
            get {
                return ResourceManager.GetString("SureToEnableRawMaterialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to enable this user?.
        /// </summary>
        public static string SureToEnableUserMessage {
            get {
                return ResourceManager.GetString("SureToEnableUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid profit per kg. Price should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string TempProfitPerKgInvalid {
            get {
                return ResourceManager.GetString("TempProfitPerKgInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit per kg  can not exceed 13 characters. Price should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string TempProfitPerKgMaxLength {
            get {
                return ResourceManager.GetString("TempProfitPerKgMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit per kg is required..
        /// </summary>
        public static string TempProfitPerKgRequired {
            get {
                return ResourceManager.GetString("TempProfitPerKgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid forwarding cost . It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string TotalForwardingCostInvalid {
            get {
                return ResourceManager.GetString("TotalForwardingCostInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding cost  can not exceed 13 characters. It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string TotalForwardingCostMaxLength {
            get {
                return ResourceManager.GetString("TotalForwardingCostMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding cost is required..
        /// </summary>
        public static string TotalForwardingCostRequired {
            get {
                return ResourceManager.GetString("TotalForwardingCostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid freight cost . It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string TotalFreightCostInvalid {
            get {
                return ResourceManager.GetString("TotalFreightCostInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight cost  can not exceed 13 characters. It should contain max 10 digit left and 2 digit right to decimal point..
        /// </summary>
        public static string TotalFreightCostMaxLength {
            get {
                return ResourceManager.GetString("TotalFreightCostMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight cost is required..
        /// </summary>
        public static string TotalFreightCostRequired {
            get {
                return ResourceManager.GetString("TotalFreightCostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid month..
        /// </summary>
        public static string TotalInterestMonthInvalid {
            get {
                return ResourceManager.GetString("TotalInterestMonthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month can not exceed 4 characters..
        /// </summary>
        public static string TotalInterestMonthMaxLength {
            get {
                return ResourceManager.GetString("TotalInterestMonthMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month is required..
        /// </summary>
        public static string TotalInterestMonthRequired {
            get {
                return ResourceManager.GetString("TotalInterestMonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Update Failed.
        /// </summary>
        public static string UpdateCustomerFailed {
            get {
                return ResourceManager.GetString("UpdateCustomerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Update Succeeded.
        /// </summary>
        public static string UpdateCustomerSucceeded {
            get {
                return ResourceManager.GetString("UpdateCustomerSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is updated successfully..
        /// </summary>
        public static string UpdateCustomerSuccesMessage {
            get {
                return ResourceManager.GetString("UpdateCustomerSuccesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product Failed.
        /// </summary>
        public static string UpdateProductFailed {
            get {
                return ResourceManager.GetString("UpdateProductFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product Sample Failed.
        /// </summary>
        public static string UpdateProductSampleFailed {
            get {
                return ResourceManager.GetString("UpdateProductSampleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Update Failed.
        /// </summary>
        public static string UpdateRawMaterialFailed {
            get {
                return ResourceManager.GetString("UpdateRawMaterialFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Update Failed.
        /// </summary>
        public static string UpdateUserFailed {
            get {
                return ResourceManager.GetString("UpdateUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Update Succeeded.
        /// </summary>
        public static string UpdateUserSucceeded {
            get {
                return ResourceManager.GetString("UpdateUserSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is updated successfully..
        /// </summary>
        public static string UpdateUserSuccesMessage {
            get {
                return ResourceManager.GetString("UpdateUserSuccesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD rate is invalid.
        /// </summary>
        public static string USDRateInvalid {
            get {
                return ResourceManager.GetString("USDRateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save USD Rate Failed.
        /// </summary>
        public static string USDRateSavedFailed {
            get {
                return ResourceManager.GetString("USDRateSavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD rate is saved successfully..
        /// </summary>
        public static string USDRateSavedSuccefully {
            get {
                return ResourceManager.GetString("USDRateSavedSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD Rate Saved Succeeded.
        /// </summary>
        public static string USDRateSaveSucceeded {
            get {
                return ResourceManager.GetString("USDRateSaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is disabled successfully..
        /// </summary>
        public static string UserDisabledSuccessfully {
            get {
                return ResourceManager.GetString("UserDisabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Disable Succeeded.
        /// </summary>
        public static string UserDisableSucceeded {
            get {
                return ResourceManager.GetString("UserDisableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is enabled successfully..
        /// </summary>
        public static string UserEnabledSuccessfully {
            get {
                return ResourceManager.GetString("UserEnabledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Enable Succeeded.
        /// </summary>
        public static string UserEnableSucceeded {
            get {
                return ResourceManager.GetString("UserEnableSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use. Please try with any other email address..
        /// </summary>
        public static string UserExistWithThisEmail {
            get {
                return ResourceManager.GetString("UserExistWithThisEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, We didn&apos;t recognize that username, password and host name(machine name)combination. please double-check and try again..
        /// </summary>
        public static string UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is saved successfully..
        /// </summary>
        public static string UserSavedSuccefully {
            get {
                return ResourceManager.GetString("UserSavedSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Saved Succeeded.
        /// </summary>
        public static string UserSaveSucceeded {
            get {
                return ResourceManager.GetString("UserSaveSucceeded", resourceCulture);
            }
        }
    }
}
